### ISSUE TITLE
Revert back to port 80 ?

### ISSUE THREAD

**Issue by purplecones** [mazlix/meteor-now#14]

**Comment by mazlix** [comment]
We can try, I was getting an issue I think on the now servers when doing that though. Would just need to change the `EXPOSE 3000` --> `EXPOSE 80` in the docker file and then remove the `-e PORT=3000` when we call.

**Comment by mazlix** [comment]
I also don't think that there's any advantage/reason for us to use port 80. Because I think `now` just maps whatever port you `EXPOSE` --> 80. So I'll close this.
