### ISSUE TITLE
Anyone having problems with bcrypt?

### ISSUE THREAD

**Issue by PolGuixe** [mazlix/meteor-now#27]
I am trying to deploy this demo site https://github.com/Zetoff/mantra-accounts-test

Everything works fine in when I run meteor. 

I deploy using: 
```
meteor-now -e NODE_ENV=production
```
And I get a this log: https://zetoff-accounts-material-ui-demo-ivrdrtaxvy.now.sh

I am guessing is a problem with bcrypt, but not sure.

**Comment by PolGuixe** [comment]
I found this issue related to https://github.com/meteor/meteor/issues/7512

No apparent solution.

**Comment by purplecones** [comment]
I was able to clone and deploy it here: https://mantra-accounts-test-fntitbpsdt.now.sh/

**Comment by PolGuixe** [comment]
@purplecones which process have you followed? 🤔

**Comment by purplecones** [comment]
Nothing extra, just deployed with `meteor-now -d` to watch log. Although the first deployment failed with strange error that I haven't seen before: https://mantra-accounts-test-skfrjivapf.now.sh/ 

```
Container started
Error response from daemon: network brddepl not found
```

Without changing anything I redeployed and it worked fine. Must be a `now` related issue.

**Comment by purplecones** [comment]
Created https://github.com/zeit/now-cli/issues/295 for additional insight

**Comment by purplecones** [comment]
@PolGuixe also this one https://mantra-accounts-test-xjylwlkkye.now.sh/ was deployed with
```
meteor-now -e NODE_ENV=production
```
and it also worked fine just in case you were wondering if the `NODE_ENV` flag was causing any issue

**Comment by PolGuixe** [comment]
This is the error I am getting when I run `meteor-now -e NODE_ENV=production -d`: 

```
> ▲ docker build
> Step 10 : RUN cat x* > bundle.tar.gz
>  ---> Running in 702c56bfefc5
>  ---> 07db413641f6
> Removing intermediate container 702c56bfefc5
> Step 11 : RUN tar -xzf bundle.tar.gz
>  ---> Running in bbb55e0cff0d
>
> gzip: stdin: decompression OK, trailing garbage ignored
> tar: Child returned status 2
> tar: Error is not recoverable: exiting now
> The command '/bin/sh -c tar -xzf bundle.tar.gz' returned a non-zero code: 2
```

**Comment by purplecones** [comment]
can you link the deployment url?

**Comment by PolGuixe** [comment]
here: https://zetoff-accounts-material-ui-demo-ubhnsopiet.now.sh

**Comment by purplecones** [comment]
Is this the same repo as before? https://github.com/Zetoff/mantra-accounts-test

**Comment by PolGuixe** [comment]
Yes

**Comment by purplecones** [comment]
I am able to deploy your app with 
```
meteor-now -e NODE_ENV=production -d
```
https://mantra-accounts-test-gjqhjmouiv.now.sh/

Don't think there is an issue with the app here. Are you able to deploy any meteor app using `meteor-now`? If so, can you try deploying this app again and see if you still get the error?

It might be another `now` related issue. Hard to say at this point.

**Comment by PolGuixe** [comment]
I've deployed these two: 
- https://mantra-meteor-now-deployment-test-xgpfnfeliv.now.sh
- https://meteor-now-test-quczomxioo.now.sh

And both seem fine. 

I'll try to delete and clone the back the repo with which I am having the problem.

**Comment by PolGuixe** [comment]
After deleting and cloning the repo I had the problem with, it worked.

Result: 
- https://zetoff-accounts-material-ui-demo-dtegtmwdsl.now.sh

I have no idea what was causing the problem.
